(C#) Cinema Group Project/WebUI/Models/Tickets.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entities;

namespace WebUI.Models
{
    public class Tickets
    {
        public IEnumerable<Ticket> TransactionTickets { get; set; }
    }
}

(C#) Cinema Group Project/WebUI/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Concrete;
using Domain.Entities;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class TicketController : Controller
    {
        private IShowRepository showRepository;
        private IShowSeatRepository showSeatRepository;
        private ITempTicketRepository tempTicketRepository;
        private ITicketRepository ticketRepository;

        public TicketController(IShowRepository showRepository, IShowSeatRepository showSeatRepository, ITempTicketRepository tempTicketRepository, ITicketRepository ticketRepository)
        {
            this.showRepository = showRepository;
            this.showSeatRepository = showSeatRepository;
            this.tempTicketRepository = tempTicketRepository;
            this.ticketRepository = ticketRepository;
        }

        [HttpGet]
        public ActionResult OrderTickets(long reservationID, int showID)
        {
            // Remove tickets that are still in progress of being bought older than 5 minutes
            DateTime currentDateTime = DateTime.Now;
            DateTime minusDateTime = currentDateTime.Add(new TimeSpan(0, -5, 0));
            List<TempTicket> tempTicketList = tempTicketRepository.GetTempTickets().ToList();
            List<TempTicket> oldTempTickets = new List<TempTicket>();

            foreach (var i in tempTicketList)
            {
                if (i.TimeAdded < minusDateTime)
                {
                    List<ShowSeat> showSeats = showSeatRepository.GetShowSeats(i.ShowID).ToList();
                    foreach (var j in showSeats)
                    {
                        if (i.SeatID == j.SeatID)
                        {
                            j.IsReserved = false;
                            showSeatRepository.UpdateShowSeats(j);
                            break;
                        }
                    }
                    oldTempTickets.Add(i);
                }
            }
            tempTicketRepository.DeleteTempTickets(oldTempTickets);

            Show selectedShow = showRepository.FindShow(showID);
            string soldOut = (string)TempData["SoldOut"];
            List<decimal> tarrifs = calculatePrices(selectedShow);

            // Set reservation ID for order
            Order order = new Order();
            order.ShowID = showID;
            order.ReservationID = reservationID;

            //hide name if movie is secret ----BEGIN
            //Boolean IsSecret = (Boolean)TempData["Secret"];
            bool secret = (bool)TempData["Secret"];
            if (secret != true)
            {
                ViewBag.MovieName = selectedShow.Movie.Name;
            }
            else
            {
                ViewBag.MovieName = "?";
            }
            //hide name if movie is secret ----END
            ViewBag.NormalPrice = tarrifs[0];
            ViewBag.ChildPrice = tarrifs[1];
            ViewBag.StudentPrice = tarrifs[2];
            ViewBag.SeniorPrice = tarrifs[3];
            if (soldOut != null)
            {
                ViewBag.SoldOut = soldOut;
            }

            TempData["Secret"] = secret;
            return View("OrderTickets", order);
        }

        [HttpPost]
        public ActionResult OrderTickets(Order order)
        {
            // Add a maximum of tickets that can be ordered based on database
            Show selectedShow = showRepository.FindShow(order.ShowID);
            List<TempTicket> tempTickets = new List<TempTicket>();
            int bookedTickets = ticketRepository.GetShowTickets(selectedShow.ShowID).Count();
            int reservedTickets = tempTicketRepository.GetTempTicketsShow(selectedShow.ShowID).Count();
            int totalBookedSeats = bookedTickets + reservedTickets;
            int maxSeats = selectedShow.Room.TotalSeats;
            int seatsLeft = maxSeats - totalBookedSeats;
            int max = 10;
            int numberoftickets = 0;
            if (seatsLeft < 10)
            {
                max = seatsLeft;
            }
            TempData["Show"] = selectedShow;

            List<TempTicket> existingTempTickets = tempTicketRepository.GetTempTicketsReservation(order.ReservationID).ToList();
            if (existingTempTickets != null)
            {
                tempTicketRepository.DeleteTempTickets(existingTempTickets);
            }

            //TempData["Order"] = order;
            // Check if there are tickets available
            int ticketcount = order.StudentTickets + order.SeniorTickets + order.NormalTickets + order.ChildTickets;
            if (max == 0)
            {
                TempData["SoldOut"] = "De show is helaas uitverkocht. Er zijn geen tickets meer beschikbaar.";
                return RedirectToAction("OrderTickets", new { order.ReservationID , selectedShow.ShowID});
            }
            else if (ticketcount <= 0 | ticketcount > 10)
            {
                return RedirectToAction("OrderTickets", new { order.ReservationID , selectedShow.ShowID });
            }
            else if (ticketcount > max)
            {
                TempData["SoldOut"] = "De show is bijna uitverkocht, er zijn nog maar " + max + " tickets beschikbaar!";
                return RedirectToAction("OrderTickets", new { order.ReservationID , selectedShow.ShowID });
            }
            else
            {
                List<decimal> tarrifs = calculatePrices(selectedShow);
                // Add normal tickets
                for (int i = 0; i < order.NormalTickets; i++)
                {
                    TempTicket tempTicket = new TempTicket();
                    tempTicket.Price = tarrifs[0];
                    tempTicket.TicketType = "Standaard";
                    tempTicket.ReservationID = order.ReservationID;
                    tempTicket.ShowID = selectedShow.ShowID;
                    tempTicket.TimeAdded = DateTime.Now;
                    tempTicket.Show = selectedShow;
                    tempTicket.IsPaid = false;
                    tempTicket.ShowID = selectedShow.ShowID;
                    tempTickets.Add(tempTicket);
                    numberoftickets++;
                }
                // Add child tickets
                for (int i = 0; i < order.ChildTickets; i++)
                {
                    TempTicket tempTicket = new TempTicket();
                    tempTicket.Price = tarrifs[1];
                    tempTicket.TicketType = "Kind";
                    tempTicket.ReservationID = order.ReservationID;
                    tempTicket.ShowID = selectedShow.ShowID;
                    tempTicket.TimeAdded = DateTime.Now;
                    tempTicket.Show = selectedShow;
                    tempTicket.IsPaid = false;
                    tempTicket.ShowID = selectedShow.ShowID;
                    tempTickets.Add(tempTicket);
                    numberoftickets++;
                }
                // Add student tickets
                for (int i = 0; i < order.StudentTickets; i++)
                {
                    TempTicket tempTicket = new TempTicket();
                    tempTicket.Price = tarrifs[2];
                    tempTicket.TicketType = "Student";
                    tempTicket.ReservationID = order.ReservationID;
                    tempTicket.ShowID = selectedShow.ShowID;
                    tempTicket.TimeAdded = DateTime.Now;
                    tempTicket.Show = selectedShow;
                    tempTicket.IsPaid = false;
                    tempTicket.ShowID = selectedShow.ShowID;
                    tempTickets.Add(tempTicket);
                    numberoftickets++;
                }
                // Add senior tickets
                for (int i = 0; i < order.SeniorTickets; i++)
                {
                    TempTicket tempTicket = new TempTicket();
                    tempTicket.Price = tarrifs[3];
                    tempTicket.TicketType = "Senior";
                    tempTicket.ReservationID = order.ReservationID;
                    tempTicket.ShowID = selectedShow.ShowID;
                    tempTicket.TimeAdded = DateTime.Now;
                    tempTicket.Show = selectedShow;
                    tempTicket.IsPaid = false;
                    tempTicket.ShowID = selectedShow.ShowID;
                    tempTickets.Add(tempTicket);
                    numberoftickets++;
                }
                selectedShow.NumberofTickets = selectedShow.NumberofTickets + numberoftickets;
                tempTicketRepository.SaveTempTickets(tempTickets);
                return RedirectToAction("AddPopcorn", new { order.ReservationID });
            }
        }

        [HttpGet]
        public ActionResult AddPopcorn(long reservationID)
        {
            List<TempTicket> tempTickets = tempTicketRepository.GetTempTicketsReservation(reservationID).ToList();
            List<TempTicketModel> tempTicketModel = new List<TempTicketModel>();
            Show selectedShow = showRepository.FindShow(tempTickets.FirstOrDefault().ShowID);

            foreach (var item in tempTickets)
            {
                TempTicketModel model = new TempTicketModel();
                model.ReservationID = item.ReservationID;
                model.Price = item.Price;
                model.TicketType = item.TicketType;
                model.Is3D = selectedShow.Movie.Is3D;
                tempTicketModel.Add(model);
            }
            return View("AddPopcorn", tempTicketModel);
        }

        [HttpPost]
        public ActionResult AddPopcorn(List<TempTicketModel> tickets)
        {
            List<TempTicket> ticketList = tempTicketRepository.GetTempTicketsReservation(tickets.FirstOrDefault().ReservationID).ToList();
            for (int i = 0; i < tickets.Count; i++)
            {
                if (tickets[i].Popcorn == true)
                {

(C#) Cinema Group Project/WebUI/Views/Ticket/AddPopcorn.cshtml
@model  List<WebUI.Models.TempTicketModel>

@{
    ViewBag.Title = "AddPopcorn";
}

<body>
    <div class="text-center">
        <p>
        <h2>Voeg popcorn toe!</h2><br />
        <p>Voor €5,- krijg je popcorn + fris! Los kost dit €6,-!</p>
        @if (Model.FirstOrDefault().Is3D == true)
        {
            <p>Jullie film is een 3D film. Hiervoor is een 3D bril nodig, deze kost €2,-.</p>
            <p>Kies bij welke tickets je popcorn en een 3D bril wilt toevoegen.</p>
        }
        @if (Model.FirstOrDefault().Is3D == false)
        {
            <p>Kies bij welke tickets je popcorn wilt toevoegen.</p>
        }
        <p>Daarnaast kan je je ticket naar VIP upgraden voor €5,-. Bij een VIP ticket krijg je eigen parkeerservice en een drankje dat al voor je klaarstaat in de pauze!</p>

        </p>
        @using (Html.BeginForm("AddPopcorn", "Ticket", FormMethod.Post))
        {
        <table align="center">
            <tr>
                <th scope="col">Ticket Nummer</th>
                <th scope="col">Prijs</th>
                <th scope="col">Type</th>
                <th scope="col">Popcorn</th>
                @if (Model.FirstOrDefault().Is3D == true)
                {
                <th scope="col">3D bril</th>
                }
                <th scope="col">VIP</th>
            </tr>
            @{ int j = 0;}
            @for (int i = 0; i < Model.Count; i++)
            {
            j++;
            <tr>
                <td>
                    @j <p style="display:none">@Html.TextBoxFor(x => Model[i].ReservationID)</p>
                </td>
                <td>
                    €@Html.DisplayFor(x => Model[i].Price)
                </td>
                <td>
                    @Html.DisplayFor(x => Model[i].TicketType)
                </td>
                <td>
                    @Html.CheckBoxFor(x => Model[i].Popcorn) + €5,-
                </td>
                @if (Model.FirstOrDefault().Is3D == true)
                {
                <td>
                    @Html.CheckBoxFor(x => Model[i].Glasses, htmlAttributes: new { @checked = true }) + €2,-
                </td>
                }
                <td>
                    @Html.CheckBoxFor(x => Model[i].Vip) + €5,-
                </td>
            </tr>
            }

        </table> <br />
        <input class="btn btn-danger" type="submit" value="Voeg toe!" />
}
    </div>
</body>

(C#) Cinema Group Project/WebUI/Views/Ticket/OrderTickets.cshtml
@model WebUI.Models.Order
@{
    ViewBag.Title = "OrderTickets";
}

<body>
    <div class="text-center">
        @*<p>*@
        <br />
        <h2>Je bestelt nu tickets voor @ViewBag.MovieName</h2><br />
        <p>Selecteer het aantal gewenste tickets.</p>
        <b>Let op:</b><p>Voor het studententarief dient een geldige studentenpas getoond te worden bij de ingang!</p>
        <b>Let op:</b><p>Bestel minimaal 1 en maximaal 10 tickets!</p>
        <p style="color:red"><b>@ViewBag.SoldOut</b></p>
        @*</p>*@
        @using (Html.BeginForm())
        {
        <p style="display:none">Reservering ID: @Html.DisplayFor(x => Model.ReservationID) Show ID: @Html.DisplayFor(x => Model.ShowID) </p>
        <table align="center" style="border-spacing: 10px; border-collapse: separate;">
            <tr>
                <th scope="col">Type ticket</th>
                <th scope="col">Prijs</th>
                <th scope="col">Aantal</th>
            </tr>
            <tr>
                <td>Standaard</td>
                <td>€@ViewBag.NormalPrice</td>
                <td>@Html.TextBox("NormalTickets", 0, new { @type = "number", @min = "0", @max = "10", @style = "width:50px" })</td>
            </tr>
            <tr>
                <td>Kind</td>
                <td>€@ViewBag.ChildPrice</td>
                <td>@Html.TextBox("ChildTickets", 0, new { @type = "number", @min = "0", @max = "10", @style = "width:50px" })</td>
            </tr>
            <tr>
                <td>Student</td>
                <td>€@ViewBag.StudentPrice</td>
                <td>@Html.TextBox("StudentTickets", 0, new { @type = "number", @min = "0", @max = "10", @style = "width:50px" })</td>
            </tr>
            <tr>
                <td>Senior</td>
                <td>€@ViewBag.SeniorPrice</td>
                <td>@Html.TextBox("SeniorTickets", 0, new { @type = "number", @min = "0", @max = "10", @style = "width:50px" })</td>
            </tr>
        </table>


        <input class="btn btn-danger" type="submit" value="Bestellen" />
}
    </div>
</body>