(C#) Cinema Group Project/WebUI/Controllers/UpcomingShowController.cs
using Domain.Abstract;
using Domain.Entities;
using Ninject.Infrastructure.Language;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class UpcomingShowController : Controller
    {
        private IMovieOverviewRepository movieRepository;
        private IShowRepository showRepository;

        public UpcomingShowController(IMovieOverviewRepository movieRepository, IShowRepository showRepository)
        {
            this.movieRepository = movieRepository;
            this.showRepository = showRepository;
        }
        [HttpPost]
        public ActionResult Dofilter(string searchString, int? age, DateTime? start)
        {
            if (start.HasValue == true)
            {
                DateTime selectedDate = (DateTime)start;
                List<Show> filteredShows = showRepository.GetShows().ToList();

                if (!String.IsNullOrEmpty(searchString) && age.HasValue == true)//1
                {
                    List<Show> list = filteredShows.Where(s => s.Movie.Name.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                            | s.Movie.MainActors.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                            | s.Movie.Genre.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                            | s.Movie.MainActors.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                            | s.Movie.SubActors.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                            | s.Movie.Director.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                           && s.Movie.Age == age
                           && s.BeginTime.DayOfYear == selectedDate.DayOfYear).ToList();
                    return View("Overview", list);
                }
                else if (!String.IsNullOrEmpty(searchString) && age.HasValue == false)//2
                {
                    List<Show> list = filteredShows.Where(s => s.Movie.Name.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                            | s.Movie.MainActors.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                            | s.Movie.Genre.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                            | s.Movie.MainActors.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                            | s.Movie.SubActors.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                            | s.Movie.Director.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                            && s.BeginTime.DayOfYear == selectedDate.DayOfYear).ToList();
                    return View("Overview", list);
                }
                else if (String.IsNullOrEmpty(searchString) && age.HasValue == true)//7
                {
                    List<Show> list = filteredShows.Where(s => s.Movie.Age == age
                            && s.BeginTime.DayOfYear == selectedDate.DayOfYear).ToList();
                    return View("Overview", list);
                }
                else if (String.IsNullOrEmpty(searchString) && age.HasValue == false)//3
                {
                    List<Show> list = filteredShows.Where(s => s.BeginTime.DayOfYear == selectedDate.DayOfYear).ToList();
                    return View("Overview", list);
                }
            }

            if (!String.IsNullOrEmpty(searchString) | age.HasValue == true)
            {
                List<Show> filteredShows = showRepository.GetShows().ToList();

                if (!String.IsNullOrEmpty(searchString) && age.HasValue == true)
                { //6
                    List<Show> list = filteredShows.Where(s => s.Movie.Name.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                            | s.Movie.MainActors.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                            | s.Movie.Genre.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                            | s.Movie.SubActors.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                            | s.Movie.Director.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                            && s.Movie.Age == age).ToList();
                    return View("Overview", list);
                }
                else if (!String.IsNullOrEmpty(searchString) && age.HasValue == false)//4
                {
                    List<Show> list = filteredShows.Where(s => s.Movie.Name.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                           | s.Movie.MainActors.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                           | s.Movie.Genre.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                           | s.Movie.SubActors.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0
                           | s.Movie.Director.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0).ToList();
                    return View("Overview", list);
                }
                else if (age.HasValue == true && String.IsNullOrEmpty(searchString))//5
                {
                    List<Show> list = filteredShows.Where(s => s.Movie.Age == age).ToList();
                    return View("Overview", list);
                }
            }
            return RedirectToAction("Overview");
        }
        
        // GET: Overview
        //[HttpGet]
        public ActionResult Overview()
        {

            //int Locationid = 1;//locationid
            DateTime now = DateTime.Now;
            // The (... + 7) % 7 ensures we end up with a value in the range [0, 6]
            int daysUntilWednesday = ((int)DayOfWeek.Wednesday - (int)now.DayOfWeek + 7) % 7;
            DateTime nextWednesday = now.AddDays(daysUntilWednesday).Date;
            DateTime NextWednesday = nextWednesday.Add(new TimeSpan(23, 59, 59));
            List<Show> allShows = showRepository.GetShows().ToList();
            //Filter out shows from different location and shows that are not of type 0
            //List<Show> allThislocationShows = allShows.ToEnumerable().Where(s => s.Movie.LocationID == Locationid && s.ShowType == 0).ToList();
            DateTime currentDateTime = DateTime.Now;
            DateTime minusDateTime = currentDateTime.Add(new TimeSpan(0, 25, 0));
            List<Show> tempShowList = new List<Show>();

            //Filter out shows from the past or start within 25 minutes and shows that are not of type 0
            List<Show> ShowsFromNow = allShows.ToEnumerable()//was allThislocationShows
                .Where(s => s.BeginTime > minusDateTime && s.ShowType == 0).ToList();
            //Order by show date
            List<Show> ShowsFromNowOrderedByDate = ShowsFromNow.ToEnumerable()
                .OrderBy(s => s.BeginTime).ToList();
            //take shows form current movie week
            List<Show> upcomingShows = ShowsFromNowOrderedByDate.ToEnumerable()
                .Where(s => s.EndTime < NextWednesday).ToList();
                ViewBag.locid = 1;
            //return View(upcomingShows);
            return View(upcomingShows);
        }

        [ChildActionOnly]
        public ActionResult Expected()
        {
            List<Show> allShows = showRepository.GetShows().ToList();
            DateTime now = DateTime.Now;
            // The (... + 7) % 7 ensures we end up with a value in the range [0, 6]
            int daysUntilWednesday = ((int)DayOfWeek.Wednesday - (int)now.DayOfWeek + 7) % 7;
            DateTime nextWednesday = now.AddDays(daysUntilWednesday).Date;
            DateTime NextWednesday = nextWednesday.Add(new TimeSpan(23, 59, 59));
            //Three Expected shows --------BEGIN
            if (allShows.Where(s => s.BeginTime > nextWednesday).Count() >= 3)
            {
                string x = allShows.Where(s => s.BeginTime > NextWednesday).ElementAt(0).Movie.Trailer.ToString();
                byte[] x2 = allShows.Where(s => s.BeginTime > NextWednesday).ElementAt(0).Movie.Image;
                string y = allShows.Where(s => s.BeginTime > NextWednesday).ElementAt(1).Movie.Trailer.ToString();
                byte[] y2 = allShows.Where(s => s.BeginTime > NextWednesday).ElementAt(1).Movie.Image;
                string z = allShows.Where(s => s.BeginTime > NextWednesday).ElementAt(2).Movie.Trailer.ToString();
                byte[] z2 = allShows.Where(s => s.BeginTime > NextWednesday).ElementAt(2).Movie.Image;

                ViewBag.trailer1 = x;
                ViewBag.image1 = x2;
                ViewBag.trailer2 = y;
                ViewBag.image2 = y2;
                ViewBag.trailer3 = z;
                ViewBag.image3 = z2;
            }
            //Three Expected shows --------END
            return PartialView("Caroussel");
        }
        // GET: UpcomingShow
        [HttpGet]
        public ActionResult Upcoming(int locationid)
        {
            
            int Locationid = locationid; 
            DateTime now = DateTime.Now;
            DateTime EndOfDay = DateTime.Today.AddDays(1) +new TimeSpan(02,00,00);
        
            List<Show> allShows = showRepository.GetShows().ToList();

            List<Show> allThislocationShows = allShows.ToEnumerable().Where(s => s.Movie.LocationID == Locationid).ToList();
            
            //Filter out shows from the past
            List<Show> ShowsFromNow = allShows.ToEnumerable()
                .Where(s => s.BeginTime > now).ToList();

            //Order by show date
            List<Show> ShowsFromNowOrderedByDate = ShowsFromNow.ToEnumerable()
                .OrderBy(s => s.BeginTime).ToList();

            //take shows form current workday

(C#) Cinema Group Project/WebUI/Views/UpcomingShow/Caroussel.cshtml
<div class="row">
    <div class="col-sm"></div>
    <div class="col-sm">
        <div class="text-center" style="color: brown; max-width:550px;">
            <div id="verwachtefilms" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#verwachtefilms" data-slide-to="0" class="active"></li>
                    <li data-target="#verwachtefilms" data-slide-to="1"></li>
                    <li data-target="#verwachtefilms" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" style="max-height:800px;">
                    <div class="carousel-item active">
                        @if (ViewBag.trailer1 != null && ViewBag.image1 != null)
                        {
                            <a target="_blank" href="@Html.Raw(ViewBag.trailer1)"><img class="d-block w-10" src="data:image;base64,@System.Convert.ToBase64String(ViewBag.image1)" alt="First slide"></a>
                        }
                        <div class="carousel-caption d-none d-md-block">
                        </div>
                    </div>
                    <div class="carousel-item">
                        @if (ViewBag.trailer2 != null && ViewBag.image2 != null)
                        {
                            <a target="_blank" href="@Html.Raw(ViewBag.trailer2)"><img class="d-block w-10" src="data:image;base64,@System.Convert.ToBase64String(ViewBag.image2)" alt="Second slide"></a>
                        }
                        <div class="carousel-caption d-none d-md-block">
                        </div>
                    </div>
                    <div class="carousel-item">
                        @if (ViewBag.trailer3 != null && ViewBag.image3 != null)
                        {
                            <a target="_blank" href="@Html.Raw(ViewBag.trailer3)"><img class="d-block w-10" src="data:image;base64,@System.Convert.ToBase64String(ViewBag.image3)" alt="Third slide"></a>
                        }
                        <div class="carousel-caption d-none d-md-block">
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#verwachtefilms" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#verwachtefilms" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
    <div class="col-sm"></div>
</div>

(C#) Cinema Group Project/WebUI/Views/UpcomingShow/NotAvailable.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Niet meer beschikbaar - My ASP.NET Application</title>
    <link href="/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="/Content/footer-fixed.css" rel="stylesheet" type="text/css" />
    <link href="/Content/menu.css" rel="stylesheet" type="text/css" />
    <script src="/Scripts/modernizr-2.6.2.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <link href="http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.min.css" rel="stylesheet" type="text/css" />
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="http://code.jquery.com/ui/1.10.4/jquery-ui.min.js"></script>
    <script>
        window.setTimeout(function () {
            window.location.href = "/UpcomingShow/Overview?locationid=1"
    }, 5000);
    </script>
</head>
<body>

    <!--Begin Avans nav bar-->
    <nav class="nav-avans" , style="height: 60px;">
        <div class="container" }>
            <a class="navbar-brand" href="/UpcomingShow/Overview?locationid=1" style="color:black; padding: 10px; font-weight: bold;">Avans Cinema</a>
            <input action="action" class="btn btn-danger" style="float: right; padding:8px; margin-top:8px" type="button" value="Terug naar vorige scherm" onclick="window.history.go(-1); return false;" />
            <ul class="global-links">
                <li>

                </li>
            </ul>
        </div>
    </nav>
    <!--End Avans nav bar-->
    <div class="container body-content">
        <h4>Er kunnen helaas geen kaartjes meer worden besteld voor deze film.<br> 
            U wordt doorgestuurd naar de overzichtspagina</h4>


        <hr />

    </div>
    <!-- Begin Footer Avans -->
    <footer class="card-footer">
        <div class="container">
            <p style="color:aliceblue">&copy; 2018 - IVH15</p><a href="/"><img src="/Content/footer-logo90x30.png" alt="Avans Hogeschool" class="footerlogo" /></a>
        </div>
    </footer>
    <!-- End Footer Avans-->
    <script src="/Scripts/jquery-1.10.2.min.js"></script>
    <script src="/Scripts/bootstrap.min.js"></script>
</body>
</html>

(C#) Cinema Group Project/WebUI/Views/UpcomingShow/Overview.cshtml
@model IEnumerable<Domain.Entities.Show>

@{
    ViewBag.Title = "Overzicht films";
}
<div class="tooltip">
    <p>genre</p>
    <span class="tooltiptext">actie, misdaad, fantasie, kids of historisch</span>
</div>
<div class="text-center">
    <br />
    <h2>Binnenkort bij ons in de bioscoop:</h2>
</div>
@Html.Action("Expected")
<div class="text-center">
    <h2>Deze Week in de bioscoop:</h2>
</div>
<div class="container">
    @using (Html.BeginForm("Dofilter", "UpcomingShow", FormMethod.Post))
    {
        <div class="row">
            <div class="col-sm-4">
                <p>Zoek op film, <a href="#" data-toggle="tooltip" title="actie, fantasie, historisch, kids, misdaad of science fiction">genre</a>, acteur of regisseur:<br>@Html.TextBox("SearchString") </p>
                @*<select id="Genre" name="Genre">
                    <option value="">Selecteer een Genre...</option>
                    <option value="actie">actie</option>
                    <option value="fantasie">fantasie</option>
                    <option value="historisch">historisch</option>
                    <option value="kids">kids</option>
                    <option value="misdaad">misdaad</option>
                    <option value="science fiction">science fiction</option>
                </select>*@
            </div>
            <div class="col-sm-4">
                <p>Zoek op datum: <br> @Html.TextBox("Start", null, new { @class = "date-picker" }) </p>
            </div>
            <div class="col-sm-4">
                <p>
                    Zoek op leeftijd:<br>
                    @Html.RadioButton("Age", 4) <span>AL</span>
                    @Html.RadioButton("Age", 6) <span>6</span>
                    @Html.RadioButton("Age", 12) <span>12</span>
                    @Html.RadioButton("Age", 16) <span>16+</span><br>
                </p>
            </div>
        </div>
        <input type="submit" class="btn btn-danger" value="Zoek films" />
        <button class="btn btn-danger" type='button' onclick="location.href = '@Url.Action("Overview", "UpcomingShow", new {locationid = ViewBag.locid}, null)'">Toon alle films</button>       
    }
</div>
<table class="table">
    <tr>
        <th>
            <!--Image-->
        </th>
        <th>
            <p>Naam film:</p>
        </th>
        <th>
            <p>3D:</p>
        </th>
        <th>
            <p>Taal:</p>
        </th>
        <th>
            <p>Ondertiteling:</p>
        </th>
        <th>
            <p>Lengte:</p>
        </th>
        <th>
            <p>Zaal:</p>
        </th>
        <th>
            <p>Leeftijd:</p>
        </th>
        <th>
            <p>Genre:</p>
        </th>
        <th>
            <p>Aanvangstijd:</p>
        </th>
        <th>
            <p>Eindtijd:</p>
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <img src="data:image;base64,@System.Convert.ToBase64String(item.Movie.Image)" width="60" height="80" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Movie.Name)
            </td>
            <td>
                @if (item.Movie.Is3D == true)
                {
                    <p>3D</p>
                }
                else
                {
                    <p></p>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Movie.Language)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Movie.LanguageSub)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Movie.Length)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Room.RoomID)
            </td>
            <td>
                @if (item.Movie.Age >= 16)
                {
                    <img src="~/Content/kijkwijzer-16.png" alt="16" height="25" width="25" />
                }
                else if (item.Movie.Age == 12)
                {
                    <img src="~/Content/kijkwijzer-12.png" alt="12" height="25" width="25" />
                }
                else if (item.Movie.Age == 6)
                {
                    <img src="~/Content/kijkwijzer-6.png" alt="6" height="25" width="25" />
                }
                else if (item.Movie.Age < 6)
                {
                    <img src="~/Content/kijkwijzer-AL.png" alt="AL" height="25" width="25" />
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Movie.Genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BeginTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndTime)
            </td>
            <td>
                <button class="btn btn-danger" type="button" onclick="location.href = '@Url.Action("ShowDetails", "UpcomingShow", new { id = item.ShowID}, null)'">Bekijk</button>
            </td>
        </tr>
    }

</table>
<script>
    $(document).ready(function)(){
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>

(C#) Cinema Group Project/WebUI/Views/UpcomingShow/ShowDetails.cshtml
@model Domain.Entities.Show

@{
    ViewBag.Title = "Details - "+Model.Movie.Name;
}

<div>
    <h4>@Html.DisplayFor(model => model.Movie.Name)</h4>
    <!-- IMDB plugin BEGIN-->
    <span class="imdbRatingPlugin" data-user="ur86663828" data-title="@Model.Movie.IMDB" data-style="p4">
        <a href="@Model.Movie.Website">
            <img src="~/Content/imdb_logo.png" alt="@Html.DisplayFor(model => model.Movie.Name)" />
        </a>
    </span>
    <script>(function (d, s, id) { var js, stags = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) { return; } js = d.createElement(s); js.id = id; js.src = "https://ia.media-imdb.com/images/G/01/imdb/plugins/rating/js/rating.js"; stags.parentNode.insertBefore(js, stags); })(document, 'script', 'imdb-rating-api');</script>
    <!-- IMDB plugin END-->
    <hr />

    <div class="container">
        <div class="row">
            <div class="col-sm">
                <img src="data:image;base64,@System.Convert.ToBase64String(Model.Movie.Image)" width="350" height="550" />
            </div>            
            <div class="col-sm">
                <dl class="dl-vertical">
                    <dt>
                        Leeftijd
                    </dt>
                    <dd>
                        @if (Model.Movie.Age >= 16)
                        {
                            <img src="~/Content/kijkwijzer-16.png" alt="16" height="25" width="25" />
                        }
                        else if (Model.Movie.Age == 12)
                        {
                            <img src="~/Content/kijkwijzer-12.png" alt="12" height="25" width="25" />
                        }
                        else if (Model.Movie.Age == 6)
                        {
                            <img src="~/Content/kijkwijzer-6.png" alt="6" height="25" width="25" />
                        }
                        else if (Model.Movie.Age < 6)
                        {
                            <img src="~/Content/kijkwijzer-AL.png" alt="AL" height="25" width="25" />
                        }
                    </dd>
                    <dt>
                        Type film(3D of normaal)
                    </dt>
                    <dd>
                        @if (Model.Movie.Is3D == true)
                        {
                         <p>3D</p>
                        }
                        else
                        {
                        <p>Normaal</p>
                        }
                    </dd>
                    <dt>
                        Taal
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Movie.Language)
                    </dd>
                    <dt>
                        Hoofdacteurs
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Movie.MainActors)
                    </dd>
                    <dt>
                        Bijrollen
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Movie.SubActors)
                    </dd>
                    <dt>
                        Regisseur
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Movie.Director)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Movie.Genre)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Movie.Genre)
                    </dd>
                </dl>
                <p>
                <button class="btn btn-danger" type="button" onclick="location.href = '@Url.Action("OrderMovie", "UpcomingShow", new { id = Model.ShowID, secret = false}, null)'">Bestel kaartjes</button>
            </p>
            </div>
            <div class="col-sm">
                <iframe width="400" height="300" src="@Model.Movie.Trailer" allowfullscreen></iframe>
                <dl>
                    <dt>
                        Beschrijving
                    </dt>
                    <dd>
                        @Html.Raw(Model.Movie.Description)
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>

(C#) Cinema Group Project/WebUI/Views/UpcomingShow/Upcoming.cshtml
@model IEnumerable<Domain.Entities.Show>

@{
    ViewBag.Title = "Overzicht van eerstkomende films";
}
<div class="text-center">
    <p>
        <h2>Het aanbod van eerstkomende films in @ViewBag.Location</h2>
        <h3>Tijd: @ViewBag.DayOfWeek  @ViewBag.HourOfDay:@ViewBag.MinuteOfDay</h3>
        <button class="btn btn-danger" type="button" onclick="location.href = '@Url.Action("Reservation", "Reservation")'">Reservering ophalen</button>
    <hr />
    </p>
</div>

<table class="table">
    <tr>
        <th>
            <p>Naam film:</p>
        </th>
        <th>
            <p>3D:</p>
        </th>
        <th>
            <p>Taal:</p>
        </th>
        <th>
            <p>Ondertiteling:</p>
        </th>
        <th>
            <p>Lengte:</p>
        </th>
        <th>
            <p>Zaal:</p>
        </th>
        <th>
            <p>Leeftijd:</p>
        </th>
        <th>
            <p>Aanvangstijd:</p>
        </th>
        <th>
            <p>Eindtijd:</p>
        </th>
        <th></th>
    </tr>
    <tr>
        <td>
            <p>? - &euro;2,50 korting!</p>
        </td>
        <td>
            @if (@ViewBag.threed == false)
             {
             <p>3D</p>
             }else {
             <p></p>
             }
        </td>
        <td>
            <p>@ViewBag.language</p>
        </td>
        <td>
            <p>@ViewBag.sublanguage</p>
        </td>
        <td>
            <p>@ViewBag.length</p>
        </td>
        <td>
            <p>@ViewBag.room</p>
        </td>
        <td>
            @if (@ViewBag.age == 16)
             {
             <img src="~/Content/kijkwijzer-16.png" alt="16" height="25" width="25"/>
             }else if(@ViewBag.age == 12) {
             <img src="~/Content/kijkwijzer-12.png" alt="12" height="25" width="25"/>
             }else if(@ViewBag.age == 6)
             {
             <img src="~/Content/kijkwijzer-6.png" alt="6" height="25" width="25"/>
             }else if (@ViewBag.age < 6)
             {
             <img src="~/Content/kijkwijzer-AL.png" alt="AL" height="25" width="25"/>
             }
        </td>
        <td>
            <p>@ViewBag.begintime</p>
        </td>
        <td>
            <p>@ViewBag.endtime</p>
        </td>
        <td>
            <button class="btn btn-danger" type="button" onclick="location.href = '@Url.Action("OrderMovie", "UpcomingShow", new { id = ViewBag.showid, secret = true}, null)'">Bestel</button>
        </td>
    </tr>
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Movie.Name)
        </td>
        <td>
            @if (item.Movie.Is3D == true)
             {
             <p>3D</p>
             }else {
             <p></p>
             }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Movie.Language)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Movie.LanguageSub)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Movie.Length)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Room.RoomID)
        </td>
        <td>
            @if (item.Movie.Age == 16)
             {
             <img src="~/Content/kijkwijzer-16.png" alt="16" height="25" width="25"/>
             }else if(item.Movie.Age == 12) {
             <img src="~/Content/kijkwijzer-12.png" alt="12" height="25" width="25"/>
             }else if(item.Movie.Age == 6)
             {
             <img src="~/Content/kijkwijzer-6.png" alt="6" height="25" width="25"/>
             }else if (item.Movie.Age < 6)
             {
             <img src="~/Content/kijkwijzer-AL.png" alt="AL" height="25" width="25"/>
             }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BeginTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndTime)
        </td>
        <td>
            <button class="btn btn-danger" type="button" onclick="location.href = '@Url.Action("OrderMovie", "UpcomingShow", new { id = item.ShowID, secret = false}, null)'">Bestel</button>
        </td>
    </tr>
}

</table>