(C#) Student Meal Application/StudentApplication/Controllers/AccountStudentController.cs
using Domain;
using Domain.Abstract;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentApplication.Controllers
{
    [Authorize(Roles = "Registration")]
    public class AccountStudentController : Controller
    {
        private IStudentRepository studentRepository;

        public AccountStudentController(IStudentRepository studentRepository)
        {
            this.studentRepository = studentRepository;
        }


        // GET: AccountStudent
        [HttpGet]
        public ActionResult StepTwo()
        {
            return View();
        }

        // Creates a student entity and changes the userrole from 'Registration' to 'Registered'
        [HttpPost]
        public ActionResult StepTwo(Student student)
        {
            if (!ModelState.IsValid)
            {
                return View(student);
            }
            student.Email = User.Identity.Name;
            studentRepository.AddStudent(student);
            return RedirectToAction("AddRole", "Account");
        }
    }
}

(C#) Student Meal Application/StudentApplication/Controllers/MealManagerController.cs
using Domain;
using Domain.Abstract;
using Domain.Entities;
using StudentApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentApplication.Controllers
{
    public class MealManagerController : Controller
    {
        private IMealRepository mealRepository;
        private IStudentRepository studentRepository;
        private IStudentMealRepository studentMealRepository;

        public MealManagerController(IMealRepository mealRepository, IStudentRepository studentRepository, IStudentMealRepository studentMealRepository)
        {
            this.mealRepository = mealRepository;
            this.studentRepository = studentRepository;
            this.studentMealRepository = studentMealRepository;
        }

        // Shows the meal creation form
        [Authorize(Roles = "Registered")]
        [HttpGet]
        public ActionResult CreateMeal(DateTime dateTime)
        {
            ViewBag.dateTime = dateTime.Date.ToShortDateString();
            TempData["DateTime"] = dateTime;
            return View();
        }

        // Post the meal creation form
        [Authorize(Roles = "Registered")]
        [HttpPost]
        public ActionResult CreateMeal(Meal meal)
        {
            DateTime dateTime = (DateTime)TempData["DateTime"];
            // Check for valid modelstate otherwise return the form
            if (!ModelState.IsValid)
            {
                ViewBag.dateTime = dateTime.Date.ToShortDateString();
                TempData["DateTime"] = dateTime;
                return View();
            }
            string userName = User.Identity.Name;
            Student student = studentRepository.GetStudent(userName);
            meal.CurrentGuests = 1;
            meal.StudentId = student.StudentId;
            meal.MealDateTime = dateTime;
            mealRepository.AddMeal(meal);
            StudentMeal studentMeal = new StudentMeal {MealId = meal.MealId, StudentID = student.StudentId, Cook = true };
            studentMealRepository.AddStudentMeal(studentMeal);
            return RedirectToAction("ViewMeals", "MealOverview");
        }

        // Show meal info
        [HttpGet]
        public ActionResult MealInfo(int id)
        {
            Meal meal = mealRepository.GetMeal(id);
            List<StudentMeal> studentMeals = studentMealRepository.GetStudentMealsForMeal(meal).ToList();
            List<Student> students = new List<Student>();
            MealInfoModel mealInfoModel = new MealInfoModel { Meal = meal, StudentMeals = studentMeals};
            return View(mealInfoModel);
        }

        // Shows the form for editing a meal
        [Authorize(Roles = "Registered")]
        [HttpGet]
        public ActionResult EditMeal(int id)
        {
            // Check if the person trying to edit it is the cook, if not it will shows noaccess
            Meal meal = mealRepository.GetMeal(id);
            if (User.Identity.Name != meal.Cook.Email)
            {
                return View("NoAccess");
            }
            // If people have signed up for your meal you can't edit it anymore
            if (meal.CurrentGuests >= 2)
            {
                return View("ExistingRegistrations");
            }
            TempData["MealId"] = id;
            return View(meal);
        }

        // Posts the form for editing a meal
        [Authorize(Roles = "Registered")]
        [HttpPost]
        public ActionResult EditMeal(Meal meal)
        {
            int id = (int)TempData["MealId"];
            Meal originalMeal = mealRepository.GetMeal(id);
            // Check if the modelstate is valid otherwise return the form
            if (!ModelState.IsValid)
            {
                TempData["MealId"] = id;
                return View(originalMeal);
            }
            originalMeal.Name = meal.Name;
            originalMeal.Price = meal.Price;
            originalMeal.MaxGuests = meal.MaxGuests;
            originalMeal.Description = meal.Description;
            mealRepository.UpdateMeal(originalMeal);
            return View("Success");
        }

        // Deletes an existing meal
        [Authorize(Roles = "Registered")]
        public ActionResult DeleteMeal(int id)
        {
            Meal meal = mealRepository.GetMeal(id);
            // Check if the person trying to edit it is the cook, if not it will shows noaccess
            if (User.Identity.Name != meal.Cook.Email)
            {
                return View("NoAccess");
            }
            Student student = studentRepository.GetStudent(User.Identity.Name);
            // If people have signed up for your meal you can't edit it anymore
            if (meal.CurrentGuests >= 2)
            {
                return View("ExistingRegistrations");
            }
            StudentMeal studentMeal = studentMealRepository.GetStudentMealsForMeal(meal).FirstOrDefault();
            studentMealRepository.DeleteStudentMeal(studentMeal);
            mealRepository.DeleteMeal(meal);
            return View("Deleted");
        }
    }
}

(C#) Student Meal Application/StudentApplication/Controllers/MealOverviewController.cs
using Domain;
using Domain.Abstract;
using Domain.Entities;
using StudentApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentApplication.Controllers
{
    public class MealOverviewController : Controller
    {
        private IMealRepository mealRepository;
        private IStudentRepository studentRepository;
        private IStudentMealRepository studentMealRepository;

        public MealOverviewController(IMealRepository mealRepository, IStudentRepository studentRepository, IStudentMealRepository studentMealRepository)
        {
            this.mealRepository = mealRepository;
            this.studentRepository = studentRepository;
            this.studentMealRepository = studentMealRepository;
        }

        // GET: MealOverview
        // Show a table with the current meals
        public ActionResult ViewMeals()
        {
            DateTime now = DateTime.Now.Date;
            DateTime twoWeeks = DateTime.Today.AddDays(13);
            List<Meal> meals = mealRepository.GetMeals(now, twoWeeks).ToList();
            List<DateTime> dates = new List<DateTime>();
            for (var dt = now; dt <= twoWeeks; dt = dt.AddDays(1))
                dates.Add(dt);
            Student student = new Student();
            List<StudentMeal> studentMeals = new List<StudentMeal>();
            if (User.IsInRole("Registered"))
            {
                student = studentRepository.GetStudent(User.Identity.Name);
                studentMeals = studentMealRepository.GetStudentMealsForStudent(student).ToList();
            }
            MealModel mealModel = new MealModel { Meals = meals, Dates = dates, Student = student, StudentMeals = studentMeals};
            return View(mealModel);
        }

        // Join a created meal
        [Authorize(Roles = "Registered")]
        public ActionResult JoinMeal(int id)
        {
            Meal meal = mealRepository.GetMeal(id);
            Student student = studentRepository.GetStudent(User.Identity.Name);
            bool exists = studentMealRepository.CheckForExisitingStudentMeal(student.StudentId, meal.MealId);
            // Check if a student is already assigned to a meal, if so, you can't add another signup
            if (exists == true)
            {
                return View("Exists");
            }
            // Check if a meal is at capacity
            if (meal.CurrentGuests >= meal.MaxGuests)
            {
                return View("Full");
            }
            // If none of these conditions apply the student is added to the meal
            meal.CurrentGuests = meal.CurrentGuests + 1;
            mealRepository.UpdateMeal(meal);
            StudentMeal studentMeal = new StudentMeal { MealId = meal.MealId, StudentID = student.StudentId, Cook = false };
            studentMealRepository.AddStudentMeal(studentMeal);
            return View("Joined");
        }

        // Remove a registration for a heal
        [Authorize(Roles = "Registered")]
        public ActionResult ExitMeal(int id)
        {
            Meal meal = mealRepository.GetMeal(id);
            Student student = studentRepository.GetStudent(User.Identity.Name);
            bool exists = studentMealRepository.CheckForExisitingStudentMeal(student.StudentId, meal.MealId);
            // Check if you are actually registered to the meal
            if (exists != true)
            {
                return View("NoMeal");
            }
            meal.CurrentGuests = meal.CurrentGuests - 1;
            mealRepository.UpdateMeal(meal);
            studentMealRepository.DeleteStudentMeal(student.StudentId, meal.MealId);
            return View("Removed");
        }
    }
}

(C#) Student Meal Application/StudentApplication/Views/MealOverview/Exists.cshtml
@{
    ViewBag.Title = "Exists";
}

<body>
    <h2>Er bestaat al een inschrijving op jouw naam!</h2>
    <hr />
    <button class="btn btn-default" type="button" onclick="location.href = '@Url.Action("ViewMeals", "MealOverview")'">Terug</button>
</body>

(C#) Student Meal Application/StudentApplication/Views/MealOverview/Full.cshtml
@{
    ViewBag.Title = "Full";
}
<body>
    <h2>De inschrijvingen voor deze maaltijd zijn al vol!</h2>
    <hr />
    <button class="btn btn-default" type="button" onclick="location.href = '@Url.Action("ViewMeals", "MealOverview")'">Terug</button>
</body>

(C#) Student Meal Application/StudentApplication/Views/MealOverview/Joined.cshtml
@{
    ViewBag.Title = "Joined";
}

<body>
    <h2>De inschrijving is gelukt!</h2>
    <hr />
    <button class="btn btn-default" type="button" onclick="location.href = '@Url.Action("ViewMeals", "MealOverview")'">Terug</button>
</body>

(C#) Student Meal Application/StudentApplication/Views/MealOverview/NoMeal.cshtml
@{
    ViewBag.Title = "NoMeal";
}

<body>
    <h2>Je staat helemaal niet ingeschreven voor deze maaltijd.</h2>
    <hr />
    <button class="btn btn-default" type="button" onclick="location.href = '@Url.Action("ViewMeals", "MealOverview")'">Terug</button>
</body>

(C#) Student Meal Application/StudentApplication/Views/MealOverview/Removed.cshtml
@{
    ViewBag.Title = "Removed";
}

<body>
    <h2>Je hebt je succesvol uitgeschreven voor de maaltijd.</h2>
    <hr />
    <button class="btn btn-default" type="button" onclick="location.href = '@Url.Action("ViewMeals", "MealOverview")'">Terug</button>
</body>

(C#) Student Meal Application/StudentApplication/Views/MealOverview/ViewMeals.cshtml
@model StudentApplication.Models.MealModel

@{
    ViewBag.Title = "ViewMeals";
}

<body>
    <h2>Overzicht maaltijden</h2>
    <p>Het onderstaande schema geeft weer wie wanneer kookt en wie er mee eet.</p>
    @if (ViewContext.HttpContext.User.IsInRole("Registration"))
    {
        <p>Je registratie is nog niet compleet, je kan nu dan ook nog geen functionaliteiten gebruiken! Maak eerst je registratie af.</p>
        <button class="btn btn-danger" type="button" style="padding:8px; margin-top:8px; margin-right:16px" onclick="location.href = '@Url.Action("StepTwo", "AccountStudent", new { title = "Stap 2" })'">Maak registratie compleet</button>
        <br /><br />
    }
    <table class="table table-hover table-striped">
        <tr>
            <th>
                <p>Datum</p>
            </th>
            <th>
                <p>Naam maaltijd</p>
            </th>
            <th>
                <p>Prijs</p>
            </th>
            <th>
                <p>Kok</p>
            </th>
            <th>
                <p>Inschrijvingen</p>
            </th>
            <th>
                <p>Info</p>
            </th>
            <th>
                <p>In/Uitschrijven</p>
            </th>
        </tr>
        @foreach (var date in Model.Dates)
        {
            var meal = Model.Meals.Where(x => x.MealDateTime == date).FirstOrDefault();
            if (meal == null)
            {
                <tr>
                    <td>
                        @date.Date.ToString("dddd") @date.ToShortDateString()
                    </td>
                    <td>
                        <b>Geen maaltijd</b>
                    </td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        @if (ViewContext.HttpContext.User.IsInRole("Registered"))
                        {
                            <button class="btn btn-default" type="button" onclick="location.href = '@Url.Action("CreateMeal", "MealManager", new { dateTime = date })'">Maaltijd maken</button>
                        }
                    </td>
                </tr>
            }
            else
            {
                <tr>
                    <td>
                        @date.Date.ToString("dddd") @date.ToShortDateString()
                    </td>
                    <td>
                        @meal.Name
                    </td>
                    <td>
                        € @meal.Price
                    </td>
                    <td>
                        @if (meal.StudentId == Model.Student.StudentId)
                        {
                            <b>(ik) </b>
                        }
                        @meal.Cook.Name
                    </td>
                    <td>
                        @meal.CurrentGuests / @meal.MaxGuests
                        @if (Model.StudentMeals.Where(x => x.MealId == meal.MealId).FirstOrDefault() != null && meal.StudentId != Model.Student.StudentId)
                        {
                            <b>(Ingeschreven)</b>
                        }
                    </td>
                    <td>
                        <a href="@Url.Action("MealInfo", "MealManager", new { id = meal.MealId })" title="Info"><img src="~/Content/sprite-info.svg"></a>
                    </td>
                    <td>
                        @if (ViewContext.HttpContext.User.IsInRole("Registered"))
                        {
                            if (meal.StudentId == Model.Student.StudentId)
                            {
                                <button class="btn btn-default" type="button" onclick="location.href = '@Url.Action("EditMeal", "MealManager", new { id = meal.MealId })'">Wijzigen</button>
                                <button class="btn btn-default" type="button" onclick="location.href = '@Url.Action("DeleteMeal", "MealManager", new { id = meal.MealId })'">Verwijderen</button>
                            }
                            else if (Model.StudentMeals.Where(x => x.MealId == meal.MealId).FirstOrDefault() == null)
                            {
                                if (meal.CurrentGuests != meal.MaxGuests)
                                {
                                    <button class="btn btn-default" type="button" onclick="location.href = '@Url.Action("JoinMeal", "MealOverview", new { id = meal.MealId })'">Inschrijven</button>
                                }
                                if (meal.CurrentGuests == meal.MaxGuests)
                                {
                                    <b>Vol</b>
                                }
                            }
                            else
                            {
                                <button class="btn btn-default" type="button" onclick="location.href = '@Url.Action("ExitMeal", "MealOverview", new { id = meal.MealId })'">Uitschrijven</button>
                            }
                        }
                    </td>
                </tr>
            }
        }
    </table>
</body>